version: '3.8'

services:
  etl_service:
    build: .
    container_name: etl_service
    depends_on:
      - db
      - redis
      - es_service

  redis:
    image: redis
    container_name: redis
    volumes:
      - $HOME/data/redis/data:/var/lib/redis/data

  es_service:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es_service
    ports:
      - 9200
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - "discovery.type=single-node"
    volumes:
      - $HOME/data/es_search/data:/usr/share/elasticsearch/data

  db:
    image: postgres:13
    container_name: postgres_movies_es
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=movies_database